services:
  frankenphp:
    build:
      context: .
    container_name: contoh-laravel
    restart: always
    ports:
      - "8000:8000"
    networks:
      - contoh-db-network

networks:
  contoh-db-network:
    name: contoh-db-network
